"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import lcmtypes.phantomvision_object_t

import lcmtypes.phantomvision_lane_t

class phantomvision_measurement_t(object):
    __slots__ = ["num_lanes", "lanes", "num_objects", "objects", "hw_timestamp"]

    def __init__(self):
        self.num_lanes = 0
        self.lanes = []
        self.num_objects = 0
        self.objects = []
        self.hw_timestamp = 0

    def encode(self):
        buf = BytesIO()
        buf.write(phantomvision_measurement_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.num_lanes))
        for i0 in range(self.num_lanes):
            assert self.lanes[i0]._get_packed_fingerprint() == lcmtypes.phantomvision_lane_t._get_packed_fingerprint()
            self.lanes[i0]._encode_one(buf)
        buf.write(struct.pack(">i", self.num_objects))
        for i0 in range(self.num_objects):
            assert self.objects[i0]._get_packed_fingerprint() == lcmtypes.phantomvision_object_t._get_packed_fingerprint()
            self.objects[i0]._encode_one(buf)
        buf.write(struct.pack(">q", self.hw_timestamp))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != phantomvision_measurement_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return phantomvision_measurement_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = phantomvision_measurement_t()
        self.num_lanes = struct.unpack(">i", buf.read(4))[0]
        self.lanes = []
        for i0 in range(self.num_lanes):
            self.lanes.append(lcmtypes.phantomvision_lane_t._decode_one(buf))
        self.num_objects = struct.unpack(">i", buf.read(4))[0]
        self.objects = []
        for i0 in range(self.num_objects):
            self.objects.append(lcmtypes.phantomvision_object_t._decode_one(buf))
        self.hw_timestamp = struct.unpack(">q", buf.read(8))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if phantomvision_measurement_t in parents: return 0
        newparents = parents + [phantomvision_measurement_t]
        tmphash = (0x357bf5381b0f0a6b+ lcmtypes.phantomvision_lane_t._get_hash_recursive(newparents)+ lcmtypes.phantomvision_object_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if phantomvision_measurement_t._packed_fingerprint is None:
            phantomvision_measurement_t._packed_fingerprint = struct.pack(">Q", phantomvision_measurement_t._get_hash_recursive([]))
        return phantomvision_measurement_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

