"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import common.point_2d_t

class obstacle_traj_t(object):
    __slots__ = ["num_points", "points"]

    __typenames__ = ["int16_t", "common.point_2d_t"]

    __dimensions__ = [None, ["num_points"]]

    def __init__(self):
        self.num_points = 0
        self.points = []

    def encode(self):
        buf = BytesIO()
        buf.write(obstacle_traj_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">h", self.num_points))
        for i0 in range(self.num_points):
            assert self.points[i0]._get_packed_fingerprint() == common.point_2d_t._get_packed_fingerprint()
            self.points[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != obstacle_traj_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return obstacle_traj_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = obstacle_traj_t()
        self.num_points = struct.unpack(">h", buf.read(2))[0]
        self.points = []
        for i0 in range(self.num_points):
            self.points.append(common.point_2d_t._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if obstacle_traj_t in parents: return 0
        newparents = parents + [obstacle_traj_t]
        tmphash = (0x3a6d9959cdc32ebf+ common.point_2d_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if obstacle_traj_t._packed_fingerprint is None:
            obstacle_traj_t._packed_fingerprint = struct.pack(">Q", obstacle_traj_t._get_hash_recursive([]))
        return obstacle_traj_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

