"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import perception.lidar_3d_object_t

class lidar_3d_info_t(object):
    __slots__ = ["utime", "frequency", "object_count", "objects"]

    __typenames__ = ["int64_t", "int16_t", "int16_t", "perception.lidar_3d_object_t"]

    __dimensions__ = [None, None, None, ["object_count"]]

    def __init__(self):
        self.utime = 0
        self.frequency = 0
        self.object_count = 0
        self.objects = []

    def encode(self):
        buf = BytesIO()
        buf.write(lidar_3d_info_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qhh", self.utime, self.frequency, self.object_count))
        for i0 in range(self.object_count):
            assert self.objects[i0]._get_packed_fingerprint() == perception.lidar_3d_object_t._get_packed_fingerprint()
            self.objects[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lidar_3d_info_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lidar_3d_info_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = lidar_3d_info_t()
        self.utime, self.frequency, self.object_count = struct.unpack(">qhh", buf.read(12))
        self.objects = []
        for i0 in range(self.object_count):
            self.objects.append(perception.lidar_3d_object_t._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if lidar_3d_info_t in parents: return 0
        newparents = parents + [lidar_3d_info_t]
        tmphash = (0xc15517d6cd9ff2b8+ perception.lidar_3d_object_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if lidar_3d_info_t._packed_fingerprint is None:
            lidar_3d_info_t._packed_fingerprint = struct.pack(">Q", lidar_3d_info_t._get_hash_recursive([]))
        return lidar_3d_info_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

