# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dow_debug.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dow_debug.proto',
  package='ab.adas',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x64ow_debug.proto\x12\x07\x61\x62.adas\"\x94\x06\n\x08\x44OWDebug\x12\x16\n\x0e\x64oor_status_fl\x18\x01 \x01(\x05\x12\x16\n\x0e\x64oor_status_fr\x18\x02 \x01(\x05\x12\x16\n\x0e\x64oor_status_rl\x18\x03 \x01(\x05\x12\x16\n\x0e\x64oor_status_rr\x18\x04 \x01(\x05\x12\x16\n\x0evehicle_status\x18\x05 \x01(\x05\x12.\n\rstate_machine\x18\x06 \x01(\x0e\x32\x17.ab.adas.DOWDebug.State\x12 \n\x18meet_war_conditons_count\x18\x07 \x01(\x05\x12,\n\x08war_left\x18\x08 \x01(\x0e\x32\x1a.ab.adas.DOWDebug.WarLevel\x12-\n\twar_right\x18\t \x01(\x0e\x32\x1a.ab.adas.DOWDebug.WarLevel\x12\x12\n\ninhibition\x18\n \x01(\x05\x12=\n\x15\x64\x65\x62ug_analy_obstacles\x18\x0b \x01(\x0b\x32\x1e.ab.adas.DOWDebug.DOWObstacles\x1a\x9a\x01\n\x0b\x44OWObstacle\x12\x12\n\nposition_x\x18\x01 \x01(\x02\x12\x12\n\nposition_y\x18\x02 \x01(\x02\x12\x13\n\x0bvelocity_vx\x18\x03 \x01(\x02\x12\x13\n\x0bvelocity_vy\x18\x04 \x01(\x02\x12\x0e\n\x06length\x18\x05 \x01(\x02\x12\r\n\x05width\x18\x06 \x01(\x02\x12\r\n\x05theta\x18\x07 \x01(\x02\x12\x0b\n\x03ttc\x18\x08 \x01(\x02\x1a\\\n\x0c\x44OWObstacles\x12\x16\n\x0eobstacle_count\x18\x01 \x01(\x05\x12\x34\n\robstacle_info\x18\x02 \x03(\x0b\x32\x1d.ab.adas.DOWDebug.DOWObstacle\"^\n\x05State\x12\x07\n\x03Off\x10\x01\x12\t\n\x05\x46\x61ult\x10\x02\x12\x06\n\x02On\x10\x03\x12\x0b\n\x07Passive\x10\x04\x12\x0b\n\x07Standby\x10\x05\x12\n\n\x06\x41\x63tive\x10\x06\x12\x08\n\x04\x44OWI\x10\x07\x12\t\n\x05\x44OWII\x10\x08\"3\n\x08WarLevel\x12\x08\n\x04None\x10\x00\x12\r\n\tWarLevelI\x10\x01\x12\x0e\n\nWarLevelII\x10\x02'
)



_DOWDEBUG_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='ab.adas.DOWDebug.State',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Off', index=0, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Fault', index=1, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='On', index=2, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Passive', index=3, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Standby', index=4, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Active', index=5, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DOWI', index=6, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DOWII', index=7, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=670,
  serialized_end=764,
)
_sym_db.RegisterEnumDescriptor(_DOWDEBUG_STATE)

_DOWDEBUG_WARLEVEL = _descriptor.EnumDescriptor(
  name='WarLevel',
  full_name='ab.adas.DOWDebug.WarLevel',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='None', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WarLevelI', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WarLevelII', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=766,
  serialized_end=817,
)
_sym_db.RegisterEnumDescriptor(_DOWDEBUG_WARLEVEL)


_DOWDEBUG_DOWOBSTACLE = _descriptor.Descriptor(
  name='DOWObstacle',
  full_name='ab.adas.DOWDebug.DOWObstacle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='position_x', full_name='ab.adas.DOWDebug.DOWObstacle.position_x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position_y', full_name='ab.adas.DOWDebug.DOWObstacle.position_y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='velocity_vx', full_name='ab.adas.DOWDebug.DOWObstacle.velocity_vx', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='velocity_vy', full_name='ab.adas.DOWDebug.DOWObstacle.velocity_vy', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='length', full_name='ab.adas.DOWDebug.DOWObstacle.length', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='width', full_name='ab.adas.DOWDebug.DOWObstacle.width', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='theta', full_name='ab.adas.DOWDebug.DOWObstacle.theta', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ttc', full_name='ab.adas.DOWDebug.DOWObstacle.ttc', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=420,
  serialized_end=574,
)

_DOWDEBUG_DOWOBSTACLES = _descriptor.Descriptor(
  name='DOWObstacles',
  full_name='ab.adas.DOWDebug.DOWObstacles',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='obstacle_count', full_name='ab.adas.DOWDebug.DOWObstacles.obstacle_count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='obstacle_info', full_name='ab.adas.DOWDebug.DOWObstacles.obstacle_info', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=576,
  serialized_end=668,
)

_DOWDEBUG = _descriptor.Descriptor(
  name='DOWDebug',
  full_name='ab.adas.DOWDebug',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='door_status_fl', full_name='ab.adas.DOWDebug.door_status_fl', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='door_status_fr', full_name='ab.adas.DOWDebug.door_status_fr', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='door_status_rl', full_name='ab.adas.DOWDebug.door_status_rl', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='door_status_rr', full_name='ab.adas.DOWDebug.door_status_rr', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vehicle_status', full_name='ab.adas.DOWDebug.vehicle_status', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state_machine', full_name='ab.adas.DOWDebug.state_machine', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='meet_war_conditons_count', full_name='ab.adas.DOWDebug.meet_war_conditons_count', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='war_left', full_name='ab.adas.DOWDebug.war_left', index=7,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='war_right', full_name='ab.adas.DOWDebug.war_right', index=8,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='inhibition', full_name='ab.adas.DOWDebug.inhibition', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='debug_analy_obstacles', full_name='ab.adas.DOWDebug.debug_analy_obstacles', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_DOWDEBUG_DOWOBSTACLE, _DOWDEBUG_DOWOBSTACLES, ],
  enum_types=[
    _DOWDEBUG_STATE,
    _DOWDEBUG_WARLEVEL,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=817,
)

_DOWDEBUG_DOWOBSTACLE.containing_type = _DOWDEBUG
_DOWDEBUG_DOWOBSTACLES.fields_by_name['obstacle_info'].message_type = _DOWDEBUG_DOWOBSTACLE
_DOWDEBUG_DOWOBSTACLES.containing_type = _DOWDEBUG
_DOWDEBUG.fields_by_name['state_machine'].enum_type = _DOWDEBUG_STATE
_DOWDEBUG.fields_by_name['war_left'].enum_type = _DOWDEBUG_WARLEVEL
_DOWDEBUG.fields_by_name['war_right'].enum_type = _DOWDEBUG_WARLEVEL
_DOWDEBUG.fields_by_name['debug_analy_obstacles'].message_type = _DOWDEBUG_DOWOBSTACLES
_DOWDEBUG_STATE.containing_type = _DOWDEBUG
_DOWDEBUG_WARLEVEL.containing_type = _DOWDEBUG
DESCRIPTOR.message_types_by_name['DOWDebug'] = _DOWDEBUG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DOWDebug = _reflection.GeneratedProtocolMessageType('DOWDebug', (_message.Message,), {

  'DOWObstacle' : _reflection.GeneratedProtocolMessageType('DOWObstacle', (_message.Message,), {
    'DESCRIPTOR' : _DOWDEBUG_DOWOBSTACLE,
    '__module__' : 'dow_debug_pb2'
    # @@protoc_insertion_point(class_scope:ab.adas.DOWDebug.DOWObstacle)
    })
  ,

  'DOWObstacles' : _reflection.GeneratedProtocolMessageType('DOWObstacles', (_message.Message,), {
    'DESCRIPTOR' : _DOWDEBUG_DOWOBSTACLES,
    '__module__' : 'dow_debug_pb2'
    # @@protoc_insertion_point(class_scope:ab.adas.DOWDebug.DOWObstacles)
    })
  ,
  'DESCRIPTOR' : _DOWDEBUG,
  '__module__' : 'dow_debug_pb2'
  # @@protoc_insertion_point(class_scope:ab.adas.DOWDebug)
  })
_sym_db.RegisterMessage(DOWDebug)
_sym_db.RegisterMessage(DOWDebug.DOWObstacle)
_sym_db.RegisterMessage(DOWDebug.DOWObstacles)


# @@protoc_insertion_point(module_scope)
