# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gps_imu_info.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gps_imu_info.proto',
  package='ab.localization',
  syntax='proto2',
  serialized_pb=_b('\n\x12gps_imu_info.proto\x12\x0f\x61\x62.localization\"\xf8\x03\n\x06gpsImu\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x12\x10\n\x08latitude\x18\x03 \x01(\x01\x12\x10\n\x08\x61ltitude\x18\x04 \x01(\x02\x12\t\n\x01x\x18\x05 \x01(\x01\x12\t\n\x01y\x18\x06 \x01(\x01\x12\x0b\n\x03yaw\x18\x07 \x01(\x02\x12\x0c\n\x04roll\x18\x08 \x01(\x02\x12\r\n\x05pitch\x18\t \x01(\x02\x12\x10\n\x08yaw_rate\x18\n \x01(\x02\x12\x16\n\x0evelocity_north\x18\x0b \x01(\x02\x12\x15\n\rvelocity_east\x18\x0c \x01(\x02\x12\x15\n\rvelocity_down\x18\r \x01(\x02\x12!\n\x19\x61\x63\x63\x65leration_longitudinal\x18\x0e \x01(\x02\x12\x1c\n\x14\x61\x63\x63\x65leration_lateral\x18\x0f \x01(\x02\x12\x14\n\x0c\x61\x63\x63\x65leration\x18\x10 \x01(\x02\x12\x10\n\x08velocity\x18\x11 \x01(\x02\x12\x17\n\x0flocation_status\x18\x12 \x01(\x02\x12\x18\n\x10\x63onfidence_level\x18\x13 \x01(\x02\x12\x14\n\x0cyaw_estimate\x18\x14 \x01(\x02\x12\x1a\n\x12longitude_estimate\x18\x15 \x01(\x01\x12\x19\n\x11latitude_estimate\x18\x16 \x01(\x01\x12\x18\n\x10satellite_number\x18\x17 \x01(\x05\x12\x1c\n\x14vehicle_speed_enable\x18\x18 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GPSIMU = _descriptor.Descriptor(
  name='gpsImu',
  full_name='ab.localization.gpsImu',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='longitude', full_name='ab.localization.gpsImu.longitude', index=0,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='ab.localization.gpsImu.latitude', index=1,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='altitude', full_name='ab.localization.gpsImu.altitude', index=2,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x', full_name='ab.localization.gpsImu.x', index=3,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='ab.localization.gpsImu.y', index=4,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='yaw', full_name='ab.localization.gpsImu.yaw', index=5,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='roll', full_name='ab.localization.gpsImu.roll', index=6,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pitch', full_name='ab.localization.gpsImu.pitch', index=7,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='yaw_rate', full_name='ab.localization.gpsImu.yaw_rate', index=8,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='velocity_north', full_name='ab.localization.gpsImu.velocity_north', index=9,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='velocity_east', full_name='ab.localization.gpsImu.velocity_east', index=10,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='velocity_down', full_name='ab.localization.gpsImu.velocity_down', index=11,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='acceleration_longitudinal', full_name='ab.localization.gpsImu.acceleration_longitudinal', index=12,
      number=14, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='acceleration_lateral', full_name='ab.localization.gpsImu.acceleration_lateral', index=13,
      number=15, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='acceleration', full_name='ab.localization.gpsImu.acceleration', index=14,
      number=16, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='velocity', full_name='ab.localization.gpsImu.velocity', index=15,
      number=17, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='location_status', full_name='ab.localization.gpsImu.location_status', index=16,
      number=18, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='confidence_level', full_name='ab.localization.gpsImu.confidence_level', index=17,
      number=19, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='yaw_estimate', full_name='ab.localization.gpsImu.yaw_estimate', index=18,
      number=20, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude_estimate', full_name='ab.localization.gpsImu.longitude_estimate', index=19,
      number=21, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='latitude_estimate', full_name='ab.localization.gpsImu.latitude_estimate', index=20,
      number=22, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='satellite_number', full_name='ab.localization.gpsImu.satellite_number', index=21,
      number=23, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vehicle_speed_enable', full_name='ab.localization.gpsImu.vehicle_speed_enable', index=22,
      number=24, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=544,
)

DESCRIPTOR.message_types_by_name['gpsImu'] = _GPSIMU

gpsImu = _reflection.GeneratedProtocolMessageType('gpsImu', (_message.Message,), dict(
  DESCRIPTOR = _GPSIMU,
  __module__ = 'gps_imu_info_pb2'
  # @@protoc_insertion_point(class_scope:ab.localization.gpsImu)
  ))
_sym_db.RegisterMessage(gpsImu)


# @@protoc_insertion_point(module_scope)
